before:
  hooks:
    - go test
builds:
  - id: linux-amd64
    main: ./
    binary: groroti
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -extldflags "-static"
      - -s -w -X main.Version={{.Version}}
  - id: linux-arm64
    main: ./
    binary: groroti
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/arm64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/local/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -extldflags "-static"
      - -s -w -X main.Version={{.Version}}
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "deezer/groroti:{{ .Version }}"
      - "deezer/groroti:latest"
      - "deezer/groroti:amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=groroti"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config.toml
      - datadir/
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "deezer/groroti:{{ .Version }}"
      - "deezer/groroti:latest"
      - "deezer/groroti:arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=groroti"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config.toml
      - datadir/
checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
source:
  # https://goreleaser.com/customization/source/
  enabled: true
