apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "groroti.fullname" . }}
  labels:
    {{- include "groroti.labels" . | nindent 4 }}s
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "groroti.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "groroti.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "groroti.serviceAccountName" . }}
      strategy:
        type: Recreate
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
          - name: FRONTEND_URL
            value: {{ .Values.frontendURL }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /-/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistentVolume.enabled }}
          volumeMounts:
          - mountPath: /data
            name: data
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistentVolume.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "groroti.fullname" . }}
      {{- end }}
