apiVersion: v1
kind: Service
metadata:
  name: {{ include "groroti.fullname" . }}
  labels:
    {{- include "groroti.labels" . | nindent 4 }}
  {{- if not .Values.serviceMonitor.create }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /-/metrics
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/scheme: "http"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.ingress.tls }}
    - port: {{ .Values.service.sport }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  selector:
    {{- include "groroti.selectorLabels" . | nindent 4 }}