apiVersion: v1
kind: Service
metadata:
  name: {{ include "groroti.fullname" . }}
  labels:
    {{- include "groroti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.ingress.tls }}
    - port: {{ .Values.service.sport }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  selector:
    {{- include "groroti.selectorLabels" . | nindent 4 }}
