replicaCount: 1

image:
  repository: deezer/groroti
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.4"

serviceAccount:
  create: true

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile: 
   type: "RuntimeDefault"

service:
  type: ClusterIP
  port: 80
  sport: 443

frontendURL: https://groroti.domain.tld
tracing:
  enable: "false"
  otlp: ""

ingress:
  enabled: true
  className: ""
  annotations: {}
  # annotations:
  #  cert-manager.io/cluster-issuer: letsencrypt-dns
  hosts:
    - host: groroti.domain.tld
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: groroti-tls
      hosts:
        - groroti.domain.tld

# you need to have the serviceMonitor CRDs to allow this
serviceMonitor:
  create: false

persistentVolume:
  enabled: false
  size: 1G
  # storageClass: rook-ceph-block
  accessModes:
    - ReadWriteOnce

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
